//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendaAndTochka_dem_exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.ObjectOtchet = new HashSet<ObjectOtchet>();
            this.ObjectOtchetPay = new HashSet<ObjectOtchetPay>();
        }
    
        public int ObjectID { get; set; }
        public string ObjectStreet { get; set; }
        public string ObjectHome { get; set; }
        public string ObjectNumber { get; set; }
        public string OwnerName { get; set; }
        public string OwnerSurname { get; set; }
        public string OwnerPatronomic { get; set; }
        public string PhoneNumber { get; set; }
        public int ObjCategoryID { get; set; }
    
        public virtual ObjectCategories ObjectCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectOtchet> ObjectOtchet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectOtchetPay> ObjectOtchetPay { get; set; }
    }
}
