//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendaAndTochka_dem_exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectOtchet
    {
        public int ObjOtchStatusID { get; set; }
        public int ObjectID { get; set; }
        public int ObjStatusID { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
    
        public virtual Objects Objects { get; set; }
        public virtual ObjectStatuses ObjectStatuses { get; set; }
    }
}
