//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendaAndTochka_dem_exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectOtchetPay
    {
        public int ObjOtchPayID { get; set; }
        public int ClientID { get; set; }
        public int ObjectID { get; set; }
        public Nullable<System.DateTime> DateStartRent { get; set; }
        public Nullable<System.DateTime> DateEndRent { get; set; }
        public Nullable<decimal> Summa { get; set; }
        public Nullable<decimal> Payed { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Objects Objects { get; set; }
    }
}
