//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendaAndTochka_dem_exam.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPatronomic { get; set; }
        public int RoleID { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> LastTimeLogin { get; set; }
        public Nullable<bool> IsBlocked { get; set; }

        public virtual Roles Roles { get; set; }

    }
}

